# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.7

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/jtnunley/Programming/Projects/Branches

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/jtnunley/Programming/Projects/Branches

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jtnunley/Programming/Projects/Branches/CMakeFiles /home/jtnunley/Programming/Projects/Branches/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jtnunley/Programming/Projects/Branches/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named branches

# Build rule for target.
branches: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 branches
.PHONY : branches

# fast build rule for target.
branches/fast:
	$(MAKE) -f CMakeFiles/branches.dir/build.make CMakeFiles/branches.dir/build
.PHONY : branches/fast

src/branch.o: src/branch.c.o

.PHONY : src/branch.o

# target to build an object file
src/branch.c.o:
	$(MAKE) -f CMakeFiles/branches.dir/build.make CMakeFiles/branches.dir/src/branch.c.o
.PHONY : src/branch.c.o

src/branch.i: src/branch.c.i

.PHONY : src/branch.i

# target to preprocess a source file
src/branch.c.i:
	$(MAKE) -f CMakeFiles/branches.dir/build.make CMakeFiles/branches.dir/src/branch.c.i
.PHONY : src/branch.c.i

src/branch.s: src/branch.c.s

.PHONY : src/branch.s

# target to generate assembly for a file
src/branch.c.s:
	$(MAKE) -f CMakeFiles/branches.dir/build.make CMakeFiles/branches.dir/src/branch.c.s
.PHONY : src/branch.c.s

src/err.o: src/err.c.o

.PHONY : src/err.o

# target to build an object file
src/err.c.o:
	$(MAKE) -f CMakeFiles/branches.dir/build.make CMakeFiles/branches.dir/src/err.c.o
.PHONY : src/err.c.o

src/err.i: src/err.c.i

.PHONY : src/err.i

# target to preprocess a source file
src/err.c.i:
	$(MAKE) -f CMakeFiles/branches.dir/build.make CMakeFiles/branches.dir/src/err.c.i
.PHONY : src/err.c.i

src/err.s: src/err.c.s

.PHONY : src/err.s

# target to generate assembly for a file
src/err.c.s:
	$(MAKE) -f CMakeFiles/branches.dir/build.make CMakeFiles/branches.dir/src/err.c.s
.PHONY : src/err.c.s

src/loop.o: src/loop.c.o

.PHONY : src/loop.o

# target to build an object file
src/loop.c.o:
	$(MAKE) -f CMakeFiles/branches.dir/build.make CMakeFiles/branches.dir/src/loop.c.o
.PHONY : src/loop.c.o

src/loop.i: src/loop.c.i

.PHONY : src/loop.i

# target to preprocess a source file
src/loop.c.i:
	$(MAKE) -f CMakeFiles/branches.dir/build.make CMakeFiles/branches.dir/src/loop.c.i
.PHONY : src/loop.c.i

src/loop.s: src/loop.c.s

.PHONY : src/loop.s

# target to generate assembly for a file
src/loop.c.s:
	$(MAKE) -f CMakeFiles/branches.dir/build.make CMakeFiles/branches.dir/src/loop.c.s
.PHONY : src/loop.c.s

src/main.o: src/main.c.o

.PHONY : src/main.o

# target to build an object file
src/main.c.o:
	$(MAKE) -f CMakeFiles/branches.dir/build.make CMakeFiles/branches.dir/src/main.c.o
.PHONY : src/main.c.o

src/main.i: src/main.c.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.c.i:
	$(MAKE) -f CMakeFiles/branches.dir/build.make CMakeFiles/branches.dir/src/main.c.i
.PHONY : src/main.c.i

src/main.s: src/main.c.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.c.s:
	$(MAKE) -f CMakeFiles/branches.dir/build.make CMakeFiles/branches.dir/src/main.c.s
.PHONY : src/main.c.s

src/shortcuts.o: src/shortcuts.c.o

.PHONY : src/shortcuts.o

# target to build an object file
src/shortcuts.c.o:
	$(MAKE) -f CMakeFiles/branches.dir/build.make CMakeFiles/branches.dir/src/shortcuts.c.o
.PHONY : src/shortcuts.c.o

src/shortcuts.i: src/shortcuts.c.i

.PHONY : src/shortcuts.i

# target to preprocess a source file
src/shortcuts.c.i:
	$(MAKE) -f CMakeFiles/branches.dir/build.make CMakeFiles/branches.dir/src/shortcuts.c.i
.PHONY : src/shortcuts.c.i

src/shortcuts.s: src/shortcuts.c.s

.PHONY : src/shortcuts.s

# target to generate assembly for a file
src/shortcuts.c.s:
	$(MAKE) -f CMakeFiles/branches.dir/build.make CMakeFiles/branches.dir/src/shortcuts.c.s
.PHONY : src/shortcuts.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... branches"
	@echo "... src/branch.o"
	@echo "... src/branch.i"
	@echo "... src/branch.s"
	@echo "... src/err.o"
	@echo "... src/err.i"
	@echo "... src/err.s"
	@echo "... src/loop.o"
	@echo "... src/loop.i"
	@echo "... src/loop.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/shortcuts.o"
	@echo "... src/shortcuts.i"
	@echo "... src/shortcuts.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

